project:
  type: website
  output-dir: docs

website:
  title: "Ahmed Albarqi"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Research & Projects
      - href: visualizations.qmd
        text: Visualizations
    right:
      - icon: github
        href: https://github.com/asbarqi
      - icon: linkedin
        href: https://www.linkedin.com/in/asbarqi/
      - icon: file-earmark-person
        href: assets/files/Ahmed_Albarqi_CV.pdf

format:
  html:
    theme: litera
    toc: false
    page-layout: full
    css: assets/css/styles.css
    include-after-body:
      - assets/js/typed-role.js
