project:
  type: website
  output-dir: docs

website:
  title: "Ahmed Albarqi"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Research & Projects
      - href: visualizations.qmd
        text: Visualizations
    right:
      - icon: github
        href: https://github.com/asbarqi
      - icon: linkedin
        href: https://www.linkedin.com/in/YOUR-LINKEDIN/

format:
  html:
    theme: litera
    toc: true
