project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Research & Projects
      - href: visualizations.qmd
        text: Visualizations
    right:
      - icon: github
        href: https://github.com/asbarqi
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/asbarqi/
        target: _blank
      - icon: file-earmark-pdf
        href: assets/files/Ahmed_Albarqi_CV.pdf
        target: _blank

format:
  html:
    theme: litera
    toc: false
    page-layout: full
    css: assets/css/styles.css
    include-in-header:
      - assets/includes/head.html
    include-after-body:
      - assets/includes/after-body.html
